#!/usr/bin/env bash
# Script that audits subdomains and displays their A record values

# Ignore SC2086 for dig usage
# shellcheck disable=SC2086

domain="$1"
sub="$2"

subdomains=("www" "lb-01" "web-01" "web-02")

query() {
  local sub="$1"
  dig +nocmd ${sub}.${domain} A +noall +answer \
    | awk '{print $1, $4}'
}

show_one() {
  local sub="$1"
  local line
  line=$(query "$sub")
  echo "The subdomain $sub is a A record and points to ${line##* }"
}

if [ -z "$sub" ]; then
  for s in "${subdomains[@]}"; do
    show_one "$s"
  done
else
  show_one "$sub"
fi
