#!/usr/bin/env bash
# Transfers a file to a remote server via SCP
#scp / path/to/file username@a:/path/to/destination
#handcoded: scp -i ~/.ssh/id_rsa README.md ubuntu@54.173.231.174

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
