#!/usr/bin/env bash
# Installs nginx and sets up a Hello World page on port 80

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx restart
