#!/usr/bin/env bash
# Configures nginx to redirect /redirect_me to a YouTube video (301 redirect)

apt-get update
apt-get install -y nginx

# Add the redirect rule to default nginx config
CONFIG="/etc/nginx/sites-available/default"

sed -i "/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" "$CONFIG"

# Reload nginx using service
service nginx reload
