#!/usr/bin/env bash
# Installs and configures HAProxy with roundrobin on web-01 and web-02

apt-get update -y
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon
    maxconn 256

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http-in
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web01 <WEB_01_IP>:80 check
    server web02 <WEB_02_IP>:80 check
EOF

service haproxy restart
